[package]
name = "temporal"
version = "0.2.0"
edition = "2024"
autobins = false

[features]
default = []
client = ["dep:temporalio-client", "dep:temporalio-common"]
worker = ["client", "dep:temporalio-sdk", "dep:temporalio-workflow", "dep:temporalio-macros"]
testing = ["worker", "temporalio-sdk/testing"]

[dependencies]
temporalio-client = { version = "=1.0.0", default-features = false, optional = true }
temporalio-common = { version = "=1.0.0", default-features = false, optional = true }
temporalio-sdk = { version = "=1.0.0", default-features = false, optional = true }
temporalio-workflow = { version = "=1.0.0", default-features = false, optional = true }
temporalio-macros = { version = "=1.0.0", optional = true }

[dev-dependencies]
futures = "0.3"
serde = { version = "1", features = ["derive"] }
tokio = { version = "1", features = ["macros", "rt-multi-thread", "time", "sync"] }

[[example]]
name = "worker"
required-features = ["worker"]

[[example]]
name = "client"
required-features = ["client"]
